käyttäjät/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name="käyttäjät"

urlpatterns = [
    path('kirjaudu/', views.kirjaudu_sisään, name="sisaan"),
    path('ulos/', views.kirjaudu_ulos, name="ulos"),
    # path('luo_tili/', views.luo_tili, name="luo_tili"),
    path('salasana_vaihto/', views.salasana_vaihto, name="salasana_vaihto"),

]

ohjelma/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.index, name="index"),
    path('tyontekija/', views.lisää_työntekijä, name="lisaa_t"),
    path('poista_t/<int:pk>', views.poista_työntekijä, name="poista_t"),
    path('tyontekija/<int:pk>', views.muokkaa_työntekijää, name="muokkaa_t"),
    path('lataa_kunnat', views.lataa_kunnat, name='lataa_kunnat'),
    path('lataa_tyopisteet', views.lataa_työpisteet, name='lataa_tyopisteet'),
    path('hae_t', views.hae_tyontekijat, name="hae_t"),
]

työntekijä_hallinta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('ohjelma.urls')),
    path('kayttaja/', include('käyttäjät.urls')),
    path('admin/', admin.site.urls),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Työntekijähallinta</title>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdn.datatables.net/v/bs5/dt-2.1.6/datatables.min.css" rel="stylesheet">

    <script src="https://cdn.datatables.net/v/bs5/dt-2.1.6/datatables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/dayjs@1/dayjs.min.js"></script>
    <script src="{% static 'mk_k_tp.js' %}"></script>
  </head>
  <body>
    {% include "navbar.html" %}
    <div class="container">
        <br/>
        {% comment %} Virheilmoitukset {% endcomment %}
        {% if messages %}
          {% for message in messages %}

          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
          {% endfor %}
        {% endif %}
        {% block content %}
        
        {% endblock content %} 
        <br/>   
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}

<h1>Työntekijähallinta</h1>
<br>
<br>


{% if user.is_authenticated %}

<div class="container">
  <div class="row">
    <div class="col">
      <select class="form-select" id="kuntaValikko">
        <option value="">Kaikki kunnat</option>
        {% for k in kunnat %}
        <option>{{ k.nimi }}</option>
        {% endfor %}
      
      </select>
    </div>
    <div class="col">
      <div class="form-check">
        <input class="form-check-input tyosuhdeInput" type="radio" name="flexRadioDefault" id="flexRadioDefault1" value="" checked>
        <label class="form-check-label" for="flexRadioDefault1">Kaikki</label>
      </div>
      <div class="form-check">
        <input class="form-check-input tyosuhdeInput" type="radio" name="flexRadioDefault" id="flexRadioDefault2" value="vakituinen" >
        <label class="form-check-label" for="flexRadioDefault2">Vakituinen</label>
      </div>
      <div class="form-check">
        <input class="form-check-input tyosuhdeInput" type="radio" name="flexRadioDefault" id="flexRadioDefault3" value="määräaikainen">
        <label class="form-check-label" for="flexRadioDefault3">Määräaikainen</label>
      </div>
    </div>
    <div class="col">
      <div class="form-check">
        <input class="form-check-input aikaInput" type="checkbox" value="e" id="entinen" checked>
        <label class="form-check-label" for="entinen">
          Entinen
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input aikaInput" type="checkbox" value="n" id="nykyinen" checked>
        <label class="form-check-label" for="nykyinen">
          Nykyinen
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input aikaInput" type="checkbox" value="t" id="tuleva" checked>
        <label class="form-check-label" for="tuleva">
          Tuleva
        </label>
      </div>
    </div>
  </div>
</div>


  <table id="tTable" class="display table table-striped table-hover" data-t-url="{% url 'hae_t' %}">
    <thead>
      <tr>
        <th scope="col">Sukunimi</th>
        <th scope="col">Etunimi</th>
        <th scope="col">Aloitus pvm</th>
        <th scope="col">Lopetus pvm</th>
        <th scope="col">Työsuhde</th>
        <th scope="col">Työtehtävä</th>
        <th scope="col">Työmaakunta</th>
        <th scope="col">Työkunta</th>
        <th scope="col">Työpiste</th> 
        <th scope="col"></th> 
      </tr>
    </thead>

    
  </table>


<br>
<br>
 
{% else %}
<a class="btn btn-primary" id="nappulaSisaan" href="{% url 'käyttäjät:sisaan'%}">Kirjaudu sisään</a>
{% endif %}
{% endblock content %}    

templates/kirjaudu.html
{% extends "base.html" %}
{% block content %}

<h1>Kirjaudu</h1>
<br>
<form method="POST">
    {% csrf_token %}

    <div class="row mb-3">
      <label class="col-sm-2 col-form-label">Käyttäjätunnus</label>
      <div class="col-sm-5">
        <input type="text" id="username" name="username">
      </div>
    </div>
    <div class="row mb-3">
      <label class="col-sm-2 col-form-label">Salasana</label>
      <div class="col-sm-5">
        <input type="password" id="password" name="password">
      </div>
    </div>


    <button type="submit" id="nappulaSubmit" class="btn btn-primary">Kirjaudu sisään</button>
  </form>


{% endblock content %}

templates/kunta_lista.html
<option value="">---------</option>
{% for k in kunnat %}
<option value="{{ k.pk }}">{{ k.nimi }}</option>
{% endfor %}

templates/luo_tili.html
{% extends "base.html" %}
{% block content %}

<h1>Luo tili</h1>
<br>
<form method="POST">
    {% csrf_token %}

    <div class="row mb-3">
        <label class="col-sm-2 col-form-label">Käyttäjätunnus</label>
        <div class="col-sm-5">
            {{form.username}}
        </div>
    </div>
    <div class="row mb-3">
        <label class="col-sm-2 col-form-label">Salasana</label>
        <div class="col-sm-5">
          {{form.password1}}
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-sm-2 col-form-label">Salasana uudestaan</label>
        <div class="col-sm-5">
            {{form.password2}}
        </div>
      </div>
    
    <button type="submit" class="btn btn-primary">Luo tili</button>
</form>

{% endblock content %}

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-primary-subtle">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url "index" %}">Työntekijähallinta</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        {% if user.is_authenticated %}
        
        <li class="nav-item">
          <a class="nav-link" id="lisaaTyontekija" href="{% url "lisaa_t" %}">Lisää työntekijä</a>
        </li>
      
        {% endif %}
      </ul>
      <ul class="navbar-nav ms-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="kayttajatili" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Käyttäjätili{% if user.is_authenticated %}: {{request.user.username}}{% endif %}
          </a>
          <ul class="dropdown-menu dropdown-menu-end">
            {% if user.is_authenticated %}

            <li><a class="dropdown-item" id="vaihdaSalasana" href="{% url "käyttäjät:salasana_vaihto" %}">Vaihda salasana</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" id="kirjauduUlos" href="{% url "käyttäjät:ulos" %}">Kirjaudu ulos</a></li>
            {% else %}
            
            {% comment %} <li><a class="dropdown-item" href="{% url "käyttäjät:luo_tili" %}">Luo tili</a></li>
            <li><hr class="dropdown-divider"></li> {% endcomment %}
            <li><a class="dropdown-item" id="kirjauduSisaan" href="{% url "käyttäjät:sisaan" %}">Kirjaudu sisään</a></li>
            
            {% endif %}
          </ul>
        </li>
      </ul>

    </div>
  </div>
</nav>

templates/poista_tyontekija.html
{% extends "base.html" %}
{% block content %}

<h1>Poista työntekijä</h1>
<br>
<form method="POST">
    {% csrf_token %}

    <h3>Haluatko todella poistaa työntekijän:</h3>
    <h5> {{t.sukunimi}}, {{t.etunimi}}</h5>
    <br>
    <button type="submit" id="nappulaSubmit" class="btn btn-primary">Kyllä</button>
    <a class="btn btn-primary" id="nappulaTakaisin" href="{% url "muokkaa_t" t.id %}" role="button">Ei</a>
</form>

{% endblock content %}

templates/tyontekija.html
{% extends "base.html" %}
{% block content %}

<form  method = "POST" id="tyontekijaForm" data-kunnat-url="{% url 'lataa_kunnat' %}" data-tyopisteet-url="{% url 'lataa_tyopisteet' %}">
    {% csrf_token %}
    {{form.as_p }}

    <button class="btn btn-primary" id="nappulaTallenna" type="submit">Tallenna</button>
    <a class="btn btn-primary" id="nappulaTakaisin" href="{% url "index" %}" role="button">Takaisin</a>
    {% if t != None %}
    <a class="btn btn-warning" id="nappulaPoista" href="{% url "poista_t" t.id  %}" role="button">Poista työntekijä</a>
    {% endif %}
</form>


{% endblock content %}

templates/tyopiste_lista.html
<option value="">---------</option>
{% for t in tyopisteet %}
<option value="{{ t.pk }}">{{ t.nimi }}</option>
{% endfor %}

templates/vaihda_salasana.html
{% extends "base.html" %}
{% block content %}

<h1>Vaihda salasana</h1>
<p>Hei {{request.user.username}}!</p>
<br>
<form method="POST">
    {% csrf_token %}
    
    <div class="row mb-3">
        <label class="col-sm-2 col-form-label">Vanha salasana</label>
        <div class="col-sm-5">
            {{form.old_password}}
        </div>
    </div>
    <div class="row mb-3">
        <label class="col-sm-2 col-form-label">Uusi salasana</label>
        <div class="col-sm-5">
          {{form.new_password1}}
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-sm-2 col-form-label">Salasana uudestaan</label>
        <div class="col-sm-5">
            {{form.new_password2}}
        </div>
      </div>
    
    <button type="submit" id="nappulaSubmit" class="btn btn-primary">Vaihda salasana</button>
</form>

{% endblock content %}